#!/usr/bin/env bash
set -x

# Run as lsst_local

. cycle.env

LOADSTACK=/opt/lsst/software/stack/loadLSST.bash

SRCDIR=/opt/lsst/src
SALSTACK=/opt/lsst/sal/salbldsteps.bash


# Conda install TSSW packages that are frozen. These are seldom changed by

# Way too much output
set +x

source ${LOADSTACK} && \
    conda config --set solver libmamba && \
    conda install -c conda-forge -y \
    aiokafka \
    astroquery \
    asynctest \
    ephem \
    kafkacat \
    pre-commit \
    pytest-tornasync \
    setuptools_scm \
    astroplan

source ${LOADSTACK} && \
    conda install -c conda-forge -y \
    boto3 \
    fastavro \
    jsonschema \
    moto=5 \
    pyyaml

source ${LOADSTACK} && \
    conda install -c lsstts -y \
    ts-xml=${ts_xml} \
    ts-utils=${ts_utils} \
    ts-idl=${ts_idl}

# Rubin-env 10 already uses python-confluent-kafka 2...

source ${LOADSTACK} && \
    conda list && \
    conda install -c lsstts/label/rc -y \
    librdkafka=${librdkafka} \
    python-confluent-kafka=${python_confluent_kafka} \
    ts-salobj=${ts_salobj}

#### Clear the astropy download cache
source ${LOADSTACK} && \
    python3 -c 'from astropy.utils.data import clear_download_cache; \
    clear_download_cache()'

source ${LOADSTACK} && \
    conda install -c lsstts -y \
    ts-xml=${ts_xml} \
    ts-utils=${ts_utils} \
    ts-idl=${ts_idl}

source ${LOADSTACK} && \
    conda install -c lsstts -c lsstts/label/rc -y \
    ts-salobj=${ts_salobj}

source ${LOADSTACK} && \
    conda install -c lsstts -y \
    ts-atdome=${ts_atdome} \
    ts-atdometrajectory=${ts_atdometrajectory} \
    ts-atmcs-simulator=${ts_atmcssimulator} \
    ts-criopy=${ts_criopy} \
    ts-m1m3-utils=${ts_m1m3_utils}

source ${LOADSTACK} && \
    xml_path=$(python -c 'from lsst.ts import xml; import pathlib; print(pathlib.Path(xml.__file__).parents[0])') && \
    eups declare -m none -r ${xml_path} ts_xml ${ts_xml}  && \
    utils_path=$(python -c 'from lsst.ts import utils; import pathlib; print(pathlib.Path(utils.__file__).parents[0])') && \
    eups declare -m none -r ${utils_path} ts_utils ${ts_utils}  && \
    salobj_path=$(python -c 'from lsst.ts import salobj; import pathlib; print(pathlib.Path(salobj.__file__).parents[0])') && \
    eups declare -m none -r ${salobj_path} ts_salobj ${ts_salobj}  && \
    idl_path=$(python -c 'from lsst.ts import idl; import pathlib; print(pathlib.Path(idl.__file__).parents[0])') && \
    eups declare -m none -r ${idl_path} ts_idl ${ts_idl}_${ts_xml}_${ts_sal} && \
    atdome_path=$(python -c 'from lsst.ts import atdome; import pathlib; print(pathlib.Path(atdome.__file__).parents[0])') && \
    eups declare -m none -r ${atdome_path} ts_atdome ${ts_atdome} && \
    atdometrajectory_path=$(python -c 'from lsst.ts import atdometrajectory; import pathlib; print(pathlib.Path(atdometrajectory.__file__).parents[0])') && \
    eups declare -m none -r ${atdometrajectory_path} ts_atdometrajectory ${ts_atdometrajectory} && \
    criopy_path=$(python -c 'from lsst.ts import criopy; import pathlib; print(pathlib.Path(criopy.__file__).parents[0])') && \
    eups declare -m none -r ${criopy_path} ts_criopy ${ts_criopy} && \
    atmcssimulator_path=$(python -c 'from lsst.ts import atmcssimulator; import pathlib; print(pathlib.Path(atmcssimulator.__file__).parents[0])') && \
    eups declare -m none -r ${atmcssimulator_path} ts_atmcssimulator ${ts_atmcssimulator}

# Only clone and setup the packages that are really necessary to be managed
# with eups. Everything else is installed using conda.
cd ${SRCDIR}
source ${LOADSTACK} && \
    gitsrc="ts_config_ocs:${ts_config_ocs} \
    ts_config_attcs:${ts_config_attcs} \
    ts_config_mtcalsys:${ts_config_mtcalsys} \
    ts_config_eas:${ts_config_eas} \
    ts_config_latiss:${ts_config_latiss} \
    ts_config_mttcs:${ts_config_mttcs} \
    ts_config_atcalsys:${ts_config_atcalsys} \
    ts_observatory_control:${ts_observatory_control} \
    ts_standardscripts:${ts_standardscripts} \
    ts_externalscripts:${ts_externalscripts}" && \
    rb="https://github.com/lsst-ts" && \
    set -e && \
    for g in $gitsrc ; do \
    r=$(echo ${g} | cut -d ':' -f 1) \
    t=$(echo ${g} | cut -d ':' -f 2) ;\
    retag=${t//a/"-alpha."} ; \
    retag=${retag//b/"-beta."} ; \
    retag=${retag//rc/"-rc."} ; \
    retag=$(echo "$retag" | sed 's/\.$//') ; \
    git clone --branch v${retag} --depth 1 --single-branch ${rb}/${r}.git ; \
    cd ${r} ; \
    git checkout -b ${t} ; \
    eups declare -r . -t current ${r} ${t}; \
    cd .. ; \
    done

set -x
# Check that packages can be imported.
source ${SALSTACK} && \
    python -c "from lsst.ts.observatory import control" && \
    python -c "from lsst.ts import standardscripts" && \
    python -c "from lsst.ts import externalscripts"
